research_task:
  description: >
    Conduct a thorough research about {profession}
    Include the technologies and concepts that would be a part of {profession}
    Make sure you find the best free & paid online sources to learn and practise.
  expected_output: >
    A list with 10 bullet points about the tools and technologies needed and how are they applied in {profession}.
    Guide in a step by step manner from lower to higher standard of each technology/tool required to be an {profession}
  agent: professional_guide

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Guide in a step by step manner from lower to higher standard of each technology/tool required to be an {profession}.
    Formatted as markdown without '```'
  agent: reporting_analyst
